services:
  postgres:
    image: postgres:16-alpine
    container_name: warehouses_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: warehouses_db
    ports:
      - "5435:5432"
    volumes:
      - warehouses_db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d users_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  warehouses_db: