version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: payments_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: payments_db
    ports:
      - "5435:5432"
    volumes:
      - payments_db:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d payments_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  payments_db: